#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# test/stability/cancel_loop.sh - AC7: interrupting a scan, over and over.
#
# One psql session opens an S3-backed foreign table on a fixture and scans it,
# and every round that scan is interrupted - half the rounds by
# statement_timeout, half by pg_cancel_backend() from another connection.  What
# is under test is that the interrupt arrives at all (the wrapper checks for
# interrupts at every Arrow batch boundary), that it arrives within a bounded
# time, that the same session still works afterwards, that nothing dumped core,
# and that the coordinator and all three segments are still up.  It ends by
# reading the signal masks of that backend's threads, which is the observable
# half of I5.
#
# With --scan topk the statement is a vector Top-K search instead, on a table
# set to mpp_execute 'coordinator' so that the search runs in the session's own
# backend.  A search is one long lance-c computation with no batch boundary in
# it; what is under test there is that the wrapper waits for it in a way an
# interrupt can break (PROBE-IMPL P-2).  Measured on the coordinator, because
# with all segments Cloudberry's own cancel round trip - about 380 ms on the
# three-segment demo cluster, for a pg_sleep() just as for a search - is most
# of what the client sees.
#
# Usage:
#   test/stability/cancel_loop.sh [options]
#
#   --rounds N                rounds to run                  (default 50)
#   --dataset NAME            fixture in the bucket to scan   (default big)
#   --scan full|topk          read every column of every row, or run a vector
#                             Top-K search on its emb column  (default full)
#   --max-median-latency-pct N
#                             fail when the median interrupt latency is more
#                             than N% of the fastest uninterrupted scan; needs
#                             --delay-ms auto                 (default 0, off)
#   --mode M                  timeout | cancel | both         (default both)
#   --delay-ms N|auto         how long a scan runs before the interrupt
#                                                             (default auto)
#   --deadline S              seconds one round may take      (default 60)
#   --calibration-deadline S  seconds the first, uninterrupted scan may take
#                                                             (default 60)
#   --min-interrupted-pct N   fail below this share of rounds actually
#                             interrupted                     (default 80)
#   --min-threads N           fewest non-main threads the signal-mask check
#                             accepts before calling itself vacuous (default 4)
#   --db NAME                 database to work in     (default lance_stability)
#   --keep-db                 do not drop a database this run created
#
# "auto" runs one scan to warm lance's caches, times three more, and then
# interrupts each round at half the fastest of them.  The rounds all run warm,
# and warming takes more than one scan, so a single sample can still be on the
# slow tail; the fastest of three is the one that bounds how early a round can
# finish.  If a calibration scan is still running after the calibration
# deadline it is cancelled and each round is interrupted 2 s in instead.
#
# The big fixture is ~1.5 GB and is not generated by default:
#   make -C test/fixtures gen GEN_FLAGS=--with-big
#   make -C test/fixtures upload UPLOAD_FLAGS="--datasets big"
# For a dry run that only exercises this script, use --dataset large_text.
# The topk scan wants vectors_big (1M random 64-d vectors, no index), which the
# same --with-big generates; upload it with --datasets vectors_big.  For a dry
# run, --dataset vectors works.
#
set -euo pipefail

TAG=cancel_loop
# shellcheck source=test/stability/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

ROUNDS=50
DATASET=big
SCAN=full
MAX_MEDIAN_PCT=0
MODE=both
DELAY_SPEC=auto
DEADLINE=60
CAL_DEADLINE=60
MIN_PCT=80
MIN_THREADS=4
DB=lance_stability
KEEP_DB=no

need_arg() { [ "$2" -ge 2 ] || die "$1 needs a value"; }

while [ $# -gt 0 ]; do
	case "$1" in
		--rounds) need_arg "$1" $#; ROUNDS=$2; shift ;;
		--rounds=*) ROUNDS=${1#*=} ;;
		--dataset) need_arg "$1" $#; DATASET=$2; shift ;;
		--dataset=*) DATASET=${1#*=} ;;
		--scan) need_arg "$1" $#; SCAN=$2; shift ;;
		--scan=*) SCAN=${1#*=} ;;
		--max-median-latency-pct) need_arg "$1" $#; MAX_MEDIAN_PCT=$2; shift ;;
		--max-median-latency-pct=*) MAX_MEDIAN_PCT=${1#*=} ;;
		--mode) need_arg "$1" $#; MODE=$2; shift ;;
		--mode=*) MODE=${1#*=} ;;
		--delay-ms) need_arg "$1" $#; DELAY_SPEC=$2; shift ;;
		--delay-ms=*) DELAY_SPEC=${1#*=} ;;
		--deadline) need_arg "$1" $#; DEADLINE=$2; shift ;;
		--deadline=*) DEADLINE=${1#*=} ;;
		--calibration-deadline) need_arg "$1" $#; CAL_DEADLINE=$2; shift ;;
		--calibration-deadline=*) CAL_DEADLINE=${1#*=} ;;
		--min-interrupted-pct) need_arg "$1" $#; MIN_PCT=$2; shift ;;
		--min-interrupted-pct=*) MIN_PCT=${1#*=} ;;
		--min-threads) need_arg "$1" $#; MIN_THREADS=$2; shift ;;
		--min-threads=*) MIN_THREADS=${1#*=} ;;
		--db) need_arg "$1" $#; DB=$2; shift ;;
		--db=*) DB=${1#*=} ;;
		--keep-db) KEEP_DB=yes ;;
		-h|--help) usage_from_header "${BASH_SOURCE[0]}"; exit 0 ;;
		*) die "unknown argument: $1 (try --help)" ;;
	esac
	shift
done

case "$MODE" in
	timeout|cancel|both) ;;
	*) die "--mode must be timeout, cancel or both" ;;
esac
case "$SCAN" in
	full|topk) ;;
	*) die "--scan must be full or topk" ;;
esac
case "$DELAY_SPEC" in
	auto|[0-9]*) ;;
	*) die "--delay-ms must be a number of milliseconds or 'auto'" ;;
esac
case "$ROUNDS$DEADLINE$CAL_DEADLINE$MIN_PCT$MIN_THREADS$MAX_MEDIAN_PCT" in
	*[!0-9]*) die "--rounds, --deadline, --calibration-deadline, --min-interrupted-pct, --min-threads and --max-median-latency-pct take numbers" ;;
esac
if [ "$MAX_MEDIAN_PCT" -gt 0 ] && [ "$DELAY_SPEC" != auto ]; then
	die "--max-median-latency-pct compares against the calibration, so it needs --delay-ms auto"
fi
[ "$ROUNDS" -ge 1 ] || die "--rounds must be at least 1"

require_docker
require_s3

# What decides the outcome is whether the dataset is in the bucket, which the
# script finds out by opening it; a missing local copy is only a good guess at
# why, so it is a warning and not a refusal.
if [ ! -d "$ROOT/test/fixtures/data/$DATASET.lance" ]; then
	say "note: $ROOT/test/fixtures/data/$DATASET.lance is not on this host, so it may never have been uploaded"
fi

say "container=$CONTAINER rounds=$ROUNDS dataset=$DATASET scan=$SCAN mode=$MODE db=$DB"
stability_remote "$STABILITY_DIR/cancel_loop.remote.sh" \
	"ROUNDS=$ROUNDS" \
	"DATASET=$DATASET" \
	"SCAN=$SCAN" \
	"MAX_MEDIAN_PCT=$MAX_MEDIAN_PCT" \
	"MODE=$MODE" \
	"DELAY_SPEC=$DELAY_SPEC" \
	"DEADLINE=$DEADLINE" \
	"CAL_DEADLINE=$CAL_DEADLINE" \
	"MIN_PCT=$MIN_PCT" \
	"MIN_THREADS=$MIN_THREADS" \
	"DB=$DB" \
	"KEEP_DB=$KEEP_DB"
