#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# test/stability/cancel_loop.sh - AC7: interrupting a scan, over and over.
#
# One psql session opens an S3-backed foreign table on a fixture and scans it,
# and every round that scan is interrupted - half the rounds by
# statement_timeout, half by pg_cancel_backend() from another connection.  What
# is under test is that the interrupt arrives at all (the wrapper checks for
# interrupts at every Arrow batch boundary), that it arrives within a bounded
# time, that the same session still works afterwards, that nothing dumped core,
# and that the coordinator and all three segments are still up.  It ends by
# reading the signal masks of that backend's threads, which is the observable
# half of I5.
#
# Usage:
#   test/stability/cancel_loop.sh [options]
#
#   --rounds N                rounds to run                  (default 50)
#   --dataset NAME            fixture in the bucket to scan   (default big)
#   --mode M                  timeout | cancel | both         (default both)
#   --delay-ms N|auto         how long a scan runs before the interrupt
#                                                             (default auto)
#   --deadline S              seconds one round may take      (default 60)
#   --calibration-deadline S  seconds the first, uninterrupted scan may take
#                                                             (default 60)
#   --min-interrupted-pct N   fail below this share of rounds actually
#                             interrupted                     (default 80)
#   --min-threads N           fewest non-main threads the signal-mask check
#                             accepts before calling itself vacuous (default 4)
#   --db NAME                 database to work in     (default lance_stability)
#   --keep-db                 do not drop a database this run created
#
# "auto" runs one scan to warm lance's caches, times a second one, and then
# interrupts halfway into each round.  The warm-up is what makes the figure
# comparable: the rounds all run warm, and a cold first scan can take several
# times longer than any of them.  If a calibration scan is still running after
# the calibration deadline it is cancelled and each round is interrupted 2 s in
# instead.
#
# The big fixture is ~1.5 GB and is not generated by default:
#   make -C test/fixtures gen GEN_FLAGS=--with-big
#   make -C test/fixtures upload UPLOAD_FLAGS="--datasets big"
# For a dry run that only exercises this script, use --dataset large_text.
#
set -euo pipefail

TAG=cancel_loop
# shellcheck source=test/stability/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

ROUNDS=50
DATASET=big
MODE=both
DELAY_SPEC=auto
DEADLINE=60
CAL_DEADLINE=60
MIN_PCT=80
MIN_THREADS=4
DB=lance_stability
KEEP_DB=no

need_arg() { [ "$2" -ge 2 ] || die "$1 needs a value"; }

while [ $# -gt 0 ]; do
	case "$1" in
		--rounds) need_arg "$1" $#; ROUNDS=$2; shift ;;
		--rounds=*) ROUNDS=${1#*=} ;;
		--dataset) need_arg "$1" $#; DATASET=$2; shift ;;
		--dataset=*) DATASET=${1#*=} ;;
		--mode) need_arg "$1" $#; MODE=$2; shift ;;
		--mode=*) MODE=${1#*=} ;;
		--delay-ms) need_arg "$1" $#; DELAY_SPEC=$2; shift ;;
		--delay-ms=*) DELAY_SPEC=${1#*=} ;;
		--deadline) need_arg "$1" $#; DEADLINE=$2; shift ;;
		--deadline=*) DEADLINE=${1#*=} ;;
		--calibration-deadline) need_arg "$1" $#; CAL_DEADLINE=$2; shift ;;
		--calibration-deadline=*) CAL_DEADLINE=${1#*=} ;;
		--min-interrupted-pct) need_arg "$1" $#; MIN_PCT=$2; shift ;;
		--min-interrupted-pct=*) MIN_PCT=${1#*=} ;;
		--min-threads) need_arg "$1" $#; MIN_THREADS=$2; shift ;;
		--min-threads=*) MIN_THREADS=${1#*=} ;;
		--db) need_arg "$1" $#; DB=$2; shift ;;
		--db=*) DB=${1#*=} ;;
		--keep-db) KEEP_DB=yes ;;
		-h|--help) usage_from_header "${BASH_SOURCE[0]}"; exit 0 ;;
		*) die "unknown argument: $1 (try --help)" ;;
	esac
	shift
done

case "$MODE" in
	timeout|cancel|both) ;;
	*) die "--mode must be timeout, cancel or both" ;;
esac
case "$DELAY_SPEC" in
	auto|[0-9]*) ;;
	*) die "--delay-ms must be a number of milliseconds or 'auto'" ;;
esac
case "$ROUNDS$DEADLINE$CAL_DEADLINE$MIN_PCT$MIN_THREADS" in
	*[!0-9]*) die "--rounds, --deadline, --calibration-deadline, --min-interrupted-pct and --min-threads take numbers" ;;
esac
[ "$ROUNDS" -ge 1 ] || die "--rounds must be at least 1"

require_docker
require_s3

# What decides the outcome is whether the dataset is in the bucket, which the
# script finds out by opening it; a missing local copy is only a good guess at
# why, so it is a warning and not a refusal.
if [ ! -d "$ROOT/test/fixtures/data/$DATASET.lance" ]; then
	say "note: $ROOT/test/fixtures/data/$DATASET.lance is not on this host, so it may never have been uploaded"
fi

say "container=$CONTAINER rounds=$ROUNDS dataset=$DATASET mode=$MODE db=$DB"
stability_remote "$STABILITY_DIR/cancel_loop.remote.sh" \
	"ROUNDS=$ROUNDS" \
	"DATASET=$DATASET" \
	"MODE=$MODE" \
	"DELAY_SPEC=$DELAY_SPEC" \
	"DEADLINE=$DEADLINE" \
	"CAL_DEADLINE=$CAL_DEADLINE" \
	"MIN_PCT=$MIN_PCT" \
	"MIN_THREADS=$MIN_THREADS" \
	"DB=$DB" \
	"KEEP_DB=$KEEP_DB"
